version: '2'

networks: 
  default:
    driver: bridge

volumes:
  traefik-ssl:
    driver: local
  postgres-data:
    driver: local
  guacamole-data:
    driver: local

services:

  traefik:
    extends:
      file: traefik/docker-compose.yml
      service: traefik
    build:
      context: traefik/
      dockerfile: Dockerfile.armhf
    image: sofwerx/traefik:armhf
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  postgres:
    extends:
      file: docker-guacamole/docker-compose.yml
      service: postgres
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  adminer:
    extends:
      file: docker-guacamole/docker-compose.yml
      service: adminer
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=adminer"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:adminer.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  guacd:
    extends:
      file: docker-guacamole/docker-compose.yml
      service: guacd
    build:
      context: docker-guacamole/guacd/
      dockerfile: Dockerfile.armhf
    image: sofwerx/guacd:armhf
    networks:
      - default
    volumes:
      - traefik-ssl:/ssl

  guacamole:
    extends:
      file: docker-guacamole/docker-compose.yml
      service: guacamole
    build:
      context: docker-guacamole/guacamole/
      dockerfile: Dockerfile.armhf
    image: sofwerx/guacamole:armhf
    networks:
      - default
    volumes:
      - guacamole-data:/data
      - traefik-ssl:/ssl
    labels:
      - "traefik.enable=true"
      - "traefik.backend=guacamole"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:guacamole.${DNS_DOMAIN};AddPrefix:/guacamole"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

